# Generated by Django 6.1.1 on 2026-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roll_no",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150),
                ),
                (
                    "student_class",
                    models.CharField(
                        choices=[
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=200),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentRegistrationSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(default=0),
                ),
            ],
            options={
                "verbose_name": "Student Registration Sequence",
                "verbose_name_plural": "Student Registration Sequence",
            },
        ),
    ]