# Generated by Django 6.1.1 on 2026-09-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='auth_user',
        ),
    ]
