# Generated by Django 6.1.1 on 2026-09-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_section_to_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentXPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('source', models.CharField(choices=[('HOMEWORK_COMPLETED', 'Homework Completed'), ('ADMIN_INCREASE', 'Admin Increase'), ('ADMIN_DECREASE', 'Admin Decrease')], max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_xp_changes', to=settings.AUTH_USER_MODEL)),
                ('homework', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xp_transaction', to='students.studenthomework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xp_transactions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
