# Generated by Django 6.1.1 on 2026-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentxptransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentxptransaction',
            name='source',
            field=models.CharField(choices=[('HOMEWORK_COMPLETED', 'Homework Completed')], max_length=30),
        ),
    ]
