# Generated by Django 6.1.1 on 2026-09-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_ensure_student_homework_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('ClassA', 'Class A'), ('ClassB', 'Class B'), ('ClassC', 'Class C'), ('ClassD', 'Class D'), ('ClassE', 'Class E')], editable=False, max_length=20),
        ),
    ]
