# Generated by Django 6.1.1 on 2026-09-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('joining_year', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('free_days', models.JSONField(default=list)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='courses.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='courses.subject')),
            ],
        ),
    ]
