# Generated by Django 6.1.1 on 2026-09-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationsequence',
            options={'verbose_name': 'Registration Sequence', 'verbose_name_plural': 'Registration Sequence'},
        ),
    ]
