# Generated by Django 6.1.1 on 2026-09-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0004_volunteerassignment_homework_attachment_and_more'),
        ('students', '0003_remove_student_auth_user'),
        ('teachers', '0004_volunteerworksession'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.CharField(choices=[('POOR', 'Poor'), ('AVERAGE', 'Average'), ('GOOD', 'Good')], max_length=20)),
                ('feedback', models.TextField(blank=True, default='')),
                ('homework_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress_records', to='admin2.volunteerassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_progress_records', to='students.student')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress_records', to='teachers.teacher')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress_records', to='teachers.volunteerworksession')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'volunteer', 'student'), name='unique_student_progress_per_assignment')],
            },
        ),
    ]
