# Generated by Django 6.1.1 on 2026-09-18 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0005_alter_volunteerassignment_assigned_class'),
        ('attendance', '0003_alter_volunteerattendance_attendance_source_and_more'),
        ('teachers', '0005_studentprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAddedWorkAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='special_added_access', to='admin2.volunteerassignment')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='special_added_work_access', to='attendance.volunteerattendance')),
                ('special_volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_added_work_accesses', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-selected_at'],
                'constraints': [models.UniqueConstraint(fields=('special_volunteer', 'access_date'), name='unique_special_added_work_per_volunteer_day')],
            },
        ),
    ]
