# Generated by Django 6.1.1 on 2026-09-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0005_alter_volunteerassignment_assigned_class'),
        ('students', '0010_alter_student_group'),
        ('teachers', '0006_specialaddedworkaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChecking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_status', models.CharField(choices=[('DONE', 'Done'), ('NOT_DONE', 'Not Done')], max_length=20)),
                ('feedback', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_checking_records', to='admin2.volunteerassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checking_records', to='students.student')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_checking_records', to='teachers.teacher')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_checking_records', to='teachers.volunteerworksession')),
            ],
            options={
                'ordering': ['-checked_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'volunteer', 'student'), name='unique_student_checking_per_assignment')],
            },
        ),
    ]
