from django.urls import path

from .views import (
    StartAttendanceSessionView,
    CurrentAttendanceSessionView,
    EndAttendanceSessionView,
    StudentAttendanceListView,
    SaveStudentAttendanceView,
    VolunteerListView,
    CurrentVolunteerAttendanceView,
    AddVolunteerAttendanceView,
    AddPlayingDayAttendanceView,
    SaveVolunteerAttendanceView,
    TodayAttendanceSummaryView,
    AttendanceHistoryView,
)

urlpatterns = [
    path(
        "session/start/",
        StartAttendanceSessionView.as_view(),
        name="start-attendance-session",
    ),
    path(
        "session/current/",
        CurrentAttendanceSessionView.as_view(),
        name="current-attendance-session",
    ),
    path(
        "session/end/",
        EndAttendanceSessionView.as_view(),
        name="end-attendance-session",
    ),
    path(
        "students/",
        StudentAttendanceListView.as_view(),
        name="student-attendance-list",
    ),
    path(
        "students/save/",
        SaveStudentAttendanceView.as_view(),
        name="save-student-attendance",
    ),
    path(
        "volunteers/",
        VolunteerListView.as_view(),
        name="volunteer-list",
    ),
    path(
        "volunteers/current/",
        CurrentVolunteerAttendanceView.as_view(),
        name="current-volunteer-attendance",
    ),
    path(
        "volunteers/add/",
        AddVolunteerAttendanceView.as_view(),
        name="add-volunteer-attendance",
    ),
    path(
        "volunteers/add-playing-day/",
        AddPlayingDayAttendanceView.as_view(),
        name="add-playing-day-attendance",
    ),
    path(
        "volunteers/save/",
        SaveVolunteerAttendanceView.as_view(),
        name="save-volunteer-attendance",
    ),
    path(
        "summary/",
        TodayAttendanceSummaryView.as_view(),
        name="today-attendance-summary",
    ),
    path(
        "history/",
        AttendanceHistoryView.as_view(),
        name="attendance-history",
    ),
]
