# Generated by Django 6.1.1 on 2026-09-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerattendance',
            name='attendance_source',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('SPECIAL_ADDED', 'Special Added')], default='ASSIGNED', max_length=20),
        ),
    ]
