# Generated by Django 6.1.1 on 2026-09-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_volunteer_volunteerassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSessionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('photo_type', models.CharField(choices=[('STUDENT', 'Student Attendance'), ('VOLUNTEER', 'Volunteer Attendance')], max_length=20)),
                ('photo', models.ImageField(upload_to='attendance/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerDailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance', to='attendance.volunteer')),
            ],
            options={
                'ordering': ['volunteer__name'],
                'constraints': [models.UniqueConstraint(fields=('volunteer', 'date'), name='unique_volunteer_attendance_per_day')],
            },
        ),
    ]
