# Generated by Django 6.1.1 on 2026-09-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_volunteerattendance_attendance_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerattendance',
            name='attendance_source',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('SPECIAL_ADDED', 'Special Added'), ('ACCESS_WORK_SUBSTITUTE', 'Access Work Substitute'), ('PLAYING_DAY', 'Playing Day')], default='ASSIGNED', max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteerattendance',
            name='task',
            field=models.CharField(choices=[('TEACHING', 'Teaching'), ('CHECKING', 'Checking'), ('INVIGILATOR', 'Invigilator')], max_length=20),
        ),
    ]
