# Generated by Django 6.1.1 on 2026-09-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_volunteerattendance_attendance_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerattendance',
            name='attendance_source',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('SPECIAL_ADDED', 'Special Added'), ('PLAYING_DAY', 'Playing Day')], default='ASSIGNED', max_length=30),
        ),
    ]
