# Generated by Django 6.1.1 on 2026-09-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesessionphoto_volunteerdailyattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='attendance_photos/')),
                ('photo_type', models.CharField(choices=[('STUDENT', 'Student Attendance'), ('VOLUNTEER', 'Volunteer Attendance')], max_length=20)),
                ('date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
