# Generated by Django 6.1.1 on 2026-09-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceSessionPhoto',
        ),
    ]
