/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Admin2RouteImport } from './routes/admin2'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as Admin1AttendanceDashboardRouteImport } from './routes/admin1.attendance-dashboard'
import { Route as Admin1ForgotPasswordRouteImport } from './routes/admin1.forgot-password'
import { Route as Admin1HistoryRouteImport } from './routes/admin1.history'
import { Route as Admin1ResetPasswordRouteImport } from './routes/admin1.reset-password'
import { Route as Admin1SigninRouteImport } from './routes/admin1.signin'
import { Route as Admin2IndexRouteImport } from './routes/admin2.index'
import { Route as Admin2AccessRequestsRouteImport } from './routes/admin2.access-requests'
import { Route as Admin2AssignmentsRouteImport } from './routes/admin2.assignments'
import { Route as Admin2CautionRouteImport } from './routes/admin2.caution'
import { Route as Admin2DailyPngRouteImport } from './routes/admin2.daily-png'
import { Route as Admin2DashboardRouteImport } from './routes/admin2.dashboard'
import { Route as Admin2ForgotPasswordRouteImport } from './routes/admin2.forgot-password'
import { Route as Admin2HolidaysRouteImport } from './routes/admin2.holidays'
import { Route as Admin2OverviewRouteImport } from './routes/admin2.overview'
import { Route as Admin2ResetPasswordRouteImport } from './routes/admin2.reset-password'
import { Route as Admin2RosterRouteImport } from './routes/admin2.roster'
import { Route as Admin2SchoolDayStatusRouteImport } from './routes/admin2.school-day-status'
import { Route as Admin2SigninRouteImport } from './routes/admin2.signin'
import { Route as StudentSignupRouteImport } from './routes/student.signup'
import { Route as TeacherForgotPasswordRouteImport } from './routes/teacher.forgot-password'
import { Route as TeacherResetPasswordRouteImport } from './routes/teacher.reset-password'
import { Route as TeacherSigninRouteImport } from './routes/teacher.signin'
import { Route as TeacherSignupRouteImport } from './routes/teacher.signup'
import { Route as VolunteerCheckingRouteImport } from './routes/volunteer.checking'
import { Route as VolunteerDashboardRouteImport } from './routes/volunteer.dashboard'
import { Route as VolunteerRequestAccessRouteImport } from './routes/volunteer.request-access'
import { Route as VolunteerSpecialAddedRouteImport } from './routes/volunteer.special-added'
import { Route as VolunteerTeachingRouteImport } from './routes/volunteer.teaching'
import { Route as Admin2StudentsIndexRouteImport } from './routes/admin2.students.index'
import { Route as Admin2StudentsRollNoRouteImport } from './routes/admin2.students.$rollNo'
import { Route as Admin2VolunteersIndexRouteImport } from './routes/admin2.volunteers.index'
import { Route as Admin2VolunteersIdRouteImport } from './routes/admin2.volunteers.$id'
import { Route as ResetPasswordUidTokenRouteImport } from './routes/reset-password.$uid.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin2Route = Admin2RouteImport.update({
  id: '/admin2',
  path: '/admin2',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin1AttendanceDashboardRoute =
  Admin1AttendanceDashboardRouteImport.update({
    id: '/admin1/attendance-dashboard',
    path: '/admin1/attendance-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const Admin1ForgotPasswordRoute = Admin1ForgotPasswordRouteImport.update({
  id: '/admin1/forgot-password',
  path: '/admin1/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin1HistoryRoute = Admin1HistoryRouteImport.update({
  id: '/admin1/history',
  path: '/admin1/history',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin1ResetPasswordRoute = Admin1ResetPasswordRouteImport.update({
  id: '/admin1/reset-password',
  path: '/admin1/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin1SigninRoute = Admin1SigninRouteImport.update({
  id: '/admin1/signin',
  path: '/admin1/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin2IndexRoute = Admin2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2AccessRequestsRoute = Admin2AccessRequestsRouteImport.update({
  id: '/access-requests',
  path: '/access-requests',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2AssignmentsRoute = Admin2AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2CautionRoute = Admin2CautionRouteImport.update({
  id: '/caution',
  path: '/caution',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2DailyPngRoute = Admin2DailyPngRouteImport.update({
  id: '/daily-png',
  path: '/daily-png',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2DashboardRoute = Admin2DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2ForgotPasswordRoute = Admin2ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2HolidaysRoute = Admin2HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2OverviewRoute = Admin2OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2ResetPasswordRoute = Admin2ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2RosterRoute = Admin2RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2SchoolDayStatusRoute = Admin2SchoolDayStatusRouteImport.update({
  id: '/school-day-status',
  path: '/school-day-status',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2SigninRoute = Admin2SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => Admin2Route,
} as any)
const StudentSignupRoute = StudentSignupRouteImport.update({
  id: '/student/signup',
  path: '/student/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherForgotPasswordRoute = TeacherForgotPasswordRouteImport.update({
  id: '/teacher/forgot-password',
  path: '/teacher/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherResetPasswordRoute = TeacherResetPasswordRouteImport.update({
  id: '/teacher/reset-password',
  path: '/teacher/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSigninRoute = TeacherSigninRouteImport.update({
  id: '/teacher/signin',
  path: '/teacher/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSignupRoute = TeacherSignupRouteImport.update({
  id: '/teacher/signup',
  path: '/teacher/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerCheckingRoute = VolunteerCheckingRouteImport.update({
  id: '/volunteer/checking',
  path: '/volunteer/checking',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerDashboardRoute = VolunteerDashboardRouteImport.update({
  id: '/volunteer/dashboard',
  path: '/volunteer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRequestAccessRoute = VolunteerRequestAccessRouteImport.update({
  id: '/volunteer/request-access',
  path: '/volunteer/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerSpecialAddedRoute = VolunteerSpecialAddedRouteImport.update({
  id: '/volunteer/special-added',
  path: '/volunteer/special-added',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerTeachingRoute = VolunteerTeachingRouteImport.update({
  id: '/volunteer/teaching',
  path: '/volunteer/teaching',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin2StudentsIndexRoute = Admin2StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2StudentsRollNoRoute = Admin2StudentsRollNoRouteImport.update({
  id: '/students/$rollNo',
  path: '/students/$rollNo',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2VolunteersIndexRoute = Admin2VolunteersIndexRouteImport.update({
  id: '/volunteers/',
  path: '/volunteers/',
  getParentRoute: () => Admin2Route,
} as any)
const Admin2VolunteersIdRoute = Admin2VolunteersIdRouteImport.update({
  id: '/volunteers/$id',
  path: '/volunteers/$id',
  getParentRoute: () => Admin2Route,
} as any)
const ResetPasswordUidTokenRoute = ResetPasswordUidTokenRouteImport.update({
  id: '/reset-password/$uid/$token',
  path: '/reset-password/$uid/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin2': typeof Admin2RouteWithChildren
  '/toolkit': typeof ToolkitRoute
  '/admin1/attendance-dashboard': typeof Admin1AttendanceDashboardRoute
  '/admin1/forgot-password': typeof Admin1ForgotPasswordRoute
  '/admin1/history': typeof Admin1HistoryRoute
  '/admin1/reset-password': typeof Admin1ResetPasswordRoute
  '/admin1/signin': typeof Admin1SigninRoute
  '/admin2/access-requests': typeof Admin2AccessRequestsRoute
  '/admin2/assignments': typeof Admin2AssignmentsRoute
  '/admin2/caution': typeof Admin2CautionRoute
  '/admin2/daily-png': typeof Admin2DailyPngRoute
  '/admin2/dashboard': typeof Admin2DashboardRoute
  '/admin2/forgot-password': typeof Admin2ForgotPasswordRoute
  '/admin2/holidays': typeof Admin2HolidaysRoute
  '/admin2/overview': typeof Admin2OverviewRoute
  '/admin2/reset-password': typeof Admin2ResetPasswordRoute
  '/admin2/roster': typeof Admin2RosterRoute
  '/admin2/school-day-status': typeof Admin2SchoolDayStatusRoute
  '/admin2/signin': typeof Admin2SigninRoute
  '/student/signup': typeof StudentSignupRoute
  '/teacher/forgot-password': typeof TeacherForgotPasswordRoute
  '/teacher/reset-password': typeof TeacherResetPasswordRoute
  '/teacher/signin': typeof TeacherSigninRoute
  '/teacher/signup': typeof TeacherSignupRoute
  '/volunteer/checking': typeof VolunteerCheckingRoute
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/volunteer/request-access': typeof VolunteerRequestAccessRoute
  '/volunteer/special-added': typeof VolunteerSpecialAddedRoute
  '/volunteer/teaching': typeof VolunteerTeachingRoute
  '/admin2/': typeof Admin2IndexRoute
  '/admin2/students/$rollNo': typeof Admin2StudentsRollNoRoute
  '/admin2/volunteers/$id': typeof Admin2VolunteersIdRoute
  '/reset-password/$uid/$token': typeof ResetPasswordUidTokenRoute
  '/admin2/students/': typeof Admin2StudentsIndexRoute
  '/admin2/volunteers/': typeof Admin2VolunteersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/toolkit': typeof ToolkitRoute
  '/admin1/attendance-dashboard': typeof Admin1AttendanceDashboardRoute
  '/admin1/forgot-password': typeof Admin1ForgotPasswordRoute
  '/admin1/history': typeof Admin1HistoryRoute
  '/admin1/reset-password': typeof Admin1ResetPasswordRoute
  '/admin1/signin': typeof Admin1SigninRoute
  '/admin2/access-requests': typeof Admin2AccessRequestsRoute
  '/admin2/assignments': typeof Admin2AssignmentsRoute
  '/admin2/caution': typeof Admin2CautionRoute
  '/admin2/daily-png': typeof Admin2DailyPngRoute
  '/admin2/dashboard': typeof Admin2DashboardRoute
  '/admin2/forgot-password': typeof Admin2ForgotPasswordRoute
  '/admin2/holidays': typeof Admin2HolidaysRoute
  '/admin2/overview': typeof Admin2OverviewRoute
  '/admin2/reset-password': typeof Admin2ResetPasswordRoute
  '/admin2/roster': typeof Admin2RosterRoute
  '/admin2/school-day-status': typeof Admin2SchoolDayStatusRoute
  '/admin2/signin': typeof Admin2SigninRoute
  '/student/signup': typeof StudentSignupRoute
  '/teacher/forgot-password': typeof TeacherForgotPasswordRoute
  '/teacher/reset-password': typeof TeacherResetPasswordRoute
  '/teacher/signin': typeof TeacherSigninRoute
  '/teacher/signup': typeof TeacherSignupRoute
  '/volunteer/checking': typeof VolunteerCheckingRoute
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/volunteer/request-access': typeof VolunteerRequestAccessRoute
  '/volunteer/special-added': typeof VolunteerSpecialAddedRoute
  '/volunteer/teaching': typeof VolunteerTeachingRoute
  '/admin2': typeof Admin2IndexRoute
  '/admin2/students/$rollNo': typeof Admin2StudentsRollNoRoute
  '/admin2/volunteers/$id': typeof Admin2VolunteersIdRoute
  '/reset-password/$uid/$token': typeof ResetPasswordUidTokenRoute
  '/admin2/students': typeof Admin2StudentsIndexRoute
  '/admin2/volunteers': typeof Admin2VolunteersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin2': typeof Admin2RouteWithChildren
  '/toolkit': typeof ToolkitRoute
  '/admin1/attendance-dashboard': typeof Admin1AttendanceDashboardRoute
  '/admin1/forgot-password': typeof Admin1ForgotPasswordRoute
  '/admin1/history': typeof Admin1HistoryRoute
  '/admin1/reset-password': typeof Admin1ResetPasswordRoute
  '/admin1/signin': typeof Admin1SigninRoute
  '/admin2/access-requests': typeof Admin2AccessRequestsRoute
  '/admin2/assignments': typeof Admin2AssignmentsRoute
  '/admin2/caution': typeof Admin2CautionRoute
  '/admin2/daily-png': typeof Admin2DailyPngRoute
  '/admin2/dashboard': typeof Admin2DashboardRoute
  '/admin2/forgot-password': typeof Admin2ForgotPasswordRoute
  '/admin2/holidays': typeof Admin2HolidaysRoute
  '/admin2/overview': typeof Admin2OverviewRoute
  '/admin2/reset-password': typeof Admin2ResetPasswordRoute
  '/admin2/roster': typeof Admin2RosterRoute
  '/admin2/school-day-status': typeof Admin2SchoolDayStatusRoute
  '/admin2/signin': typeof Admin2SigninRoute
  '/student/signup': typeof StudentSignupRoute
  '/teacher/forgot-password': typeof TeacherForgotPasswordRoute
  '/teacher/reset-password': typeof TeacherResetPasswordRoute
  '/teacher/signin': typeof TeacherSigninRoute
  '/teacher/signup': typeof TeacherSignupRoute
  '/volunteer/checking': typeof VolunteerCheckingRoute
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/volunteer/request-access': typeof VolunteerRequestAccessRoute
  '/volunteer/special-added': typeof VolunteerSpecialAddedRoute
  '/volunteer/teaching': typeof VolunteerTeachingRoute
  '/admin2/': typeof Admin2IndexRoute
  '/admin2/students/$rollNo': typeof Admin2StudentsRollNoRoute
  '/admin2/volunteers/$id': typeof Admin2VolunteersIdRoute
  '/reset-password/$uid/$token': typeof ResetPasswordUidTokenRoute
  '/admin2/students/': typeof Admin2StudentsIndexRoute
  '/admin2/volunteers/': typeof Admin2VolunteersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin2'
    | '/toolkit'
    | '/admin1/attendance-dashboard'
    | '/admin1/forgot-password'
    | '/admin1/history'
    | '/admin1/reset-password'
    | '/admin1/signin'
    | '/admin2/access-requests'
    | '/admin2/assignments'
    | '/admin2/caution'
    | '/admin2/daily-png'
    | '/admin2/dashboard'
    | '/admin2/forgot-password'
    | '/admin2/holidays'
    | '/admin2/overview'
    | '/admin2/reset-password'
    | '/admin2/roster'
    | '/admin2/school-day-status'
    | '/admin2/signin'
    | '/student/signup'
    | '/teacher/forgot-password'
    | '/teacher/reset-password'
    | '/teacher/signin'
    | '/teacher/signup'
    | '/volunteer/checking'
    | '/volunteer/dashboard'
    | '/volunteer/request-access'
    | '/volunteer/special-added'
    | '/volunteer/teaching'
    | '/admin2/'
    | '/admin2/students/$rollNo'
    | '/admin2/volunteers/$id'
    | '/reset-password/$uid/$token'
    | '/admin2/students/'
    | '/admin2/volunteers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/toolkit'
    | '/admin1/attendance-dashboard'
    | '/admin1/forgot-password'
    | '/admin1/history'
    | '/admin1/reset-password'
    | '/admin1/signin'
    | '/admin2/access-requests'
    | '/admin2/assignments'
    | '/admin2/caution'
    | '/admin2/daily-png'
    | '/admin2/dashboard'
    | '/admin2/forgot-password'
    | '/admin2/holidays'
    | '/admin2/overview'
    | '/admin2/reset-password'
    | '/admin2/roster'
    | '/admin2/school-day-status'
    | '/admin2/signin'
    | '/student/signup'
    | '/teacher/forgot-password'
    | '/teacher/reset-password'
    | '/teacher/signin'
    | '/teacher/signup'
    | '/volunteer/checking'
    | '/volunteer/dashboard'
    | '/volunteer/request-access'
    | '/volunteer/special-added'
    | '/volunteer/teaching'
    | '/admin2'
    | '/admin2/students/$rollNo'
    | '/admin2/volunteers/$id'
    | '/reset-password/$uid/$token'
    | '/admin2/students'
    | '/admin2/volunteers'
  id:
    | '__root__'
    | '/'
    | '/admin2'
    | '/toolkit'
    | '/admin1/attendance-dashboard'
    | '/admin1/forgot-password'
    | '/admin1/history'
    | '/admin1/reset-password'
    | '/admin1/signin'
    | '/admin2/access-requests'
    | '/admin2/assignments'
    | '/admin2/caution'
    | '/admin2/daily-png'
    | '/admin2/dashboard'
    | '/admin2/forgot-password'
    | '/admin2/holidays'
    | '/admin2/overview'
    | '/admin2/reset-password'
    | '/admin2/roster'
    | '/admin2/school-day-status'
    | '/admin2/signin'
    | '/student/signup'
    | '/teacher/forgot-password'
    | '/teacher/reset-password'
    | '/teacher/signin'
    | '/teacher/signup'
    | '/volunteer/checking'
    | '/volunteer/dashboard'
    | '/volunteer/request-access'
    | '/volunteer/special-added'
    | '/volunteer/teaching'
    | '/admin2/'
    | '/admin2/students/$rollNo'
    | '/admin2/volunteers/$id'
    | '/reset-password/$uid/$token'
    | '/admin2/students/'
    | '/admin2/volunteers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Admin2Route: typeof Admin2RouteWithChildren
  ToolkitRoute: typeof ToolkitRoute
  Admin1AttendanceDashboardRoute: typeof Admin1AttendanceDashboardRoute
  Admin1ForgotPasswordRoute: typeof Admin1ForgotPasswordRoute
  Admin1HistoryRoute: typeof Admin1HistoryRoute
  Admin1ResetPasswordRoute: typeof Admin1ResetPasswordRoute
  Admin1SigninRoute: typeof Admin1SigninRoute
  StudentSignupRoute: typeof StudentSignupRoute
  TeacherForgotPasswordRoute: typeof TeacherForgotPasswordRoute
  TeacherResetPasswordRoute: typeof TeacherResetPasswordRoute
  TeacherSigninRoute: typeof TeacherSigninRoute
  TeacherSignupRoute: typeof TeacherSignupRoute
  VolunteerCheckingRoute: typeof VolunteerCheckingRoute
  VolunteerDashboardRoute: typeof VolunteerDashboardRoute
  VolunteerRequestAccessRoute: typeof VolunteerRequestAccessRoute
  VolunteerSpecialAddedRoute: typeof VolunteerSpecialAddedRoute
  VolunteerTeachingRoute: typeof VolunteerTeachingRoute
  ResetPasswordUidTokenRoute: typeof ResetPasswordUidTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin2': {
      id: '/admin2'
      path: '/admin2'
      fullPath: '/admin2'
      preLoaderRoute: typeof Admin2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin1/attendance-dashboard': {
      id: '/admin1/attendance-dashboard'
      path: '/admin1/attendance-dashboard'
      fullPath: '/admin1/attendance-dashboard'
      preLoaderRoute: typeof Admin1AttendanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin1/forgot-password': {
      id: '/admin1/forgot-password'
      path: '/admin1/forgot-password'
      fullPath: '/admin1/forgot-password'
      preLoaderRoute: typeof Admin1ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin1/history': {
      id: '/admin1/history'
      path: '/admin1/history'
      fullPath: '/admin1/history'
      preLoaderRoute: typeof Admin1HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin1/reset-password': {
      id: '/admin1/reset-password'
      path: '/admin1/reset-password'
      fullPath: '/admin1/reset-password'
      preLoaderRoute: typeof Admin1ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin1/signin': {
      id: '/admin1/signin'
      path: '/admin1/signin'
      fullPath: '/admin1/signin'
      preLoaderRoute: typeof Admin1SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin2/': {
      id: '/admin2/'
      path: '/'
      fullPath: '/admin2/'
      preLoaderRoute: typeof Admin2IndexRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/access-requests': {
      id: '/admin2/access-requests'
      path: '/access-requests'
      fullPath: '/admin2/access-requests'
      preLoaderRoute: typeof Admin2AccessRequestsRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/assignments': {
      id: '/admin2/assignments'
      path: '/assignments'
      fullPath: '/admin2/assignments'
      preLoaderRoute: typeof Admin2AssignmentsRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/caution': {
      id: '/admin2/caution'
      path: '/caution'
      fullPath: '/admin2/caution'
      preLoaderRoute: typeof Admin2CautionRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/daily-png': {
      id: '/admin2/daily-png'
      path: '/daily-png'
      fullPath: '/admin2/daily-png'
      preLoaderRoute: typeof Admin2DailyPngRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/dashboard': {
      id: '/admin2/dashboard'
      path: '/dashboard'
      fullPath: '/admin2/dashboard'
      preLoaderRoute: typeof Admin2DashboardRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/forgot-password': {
      id: '/admin2/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin2/forgot-password'
      preLoaderRoute: typeof Admin2ForgotPasswordRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/holidays': {
      id: '/admin2/holidays'
      path: '/holidays'
      fullPath: '/admin2/holidays'
      preLoaderRoute: typeof Admin2HolidaysRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/overview': {
      id: '/admin2/overview'
      path: '/overview'
      fullPath: '/admin2/overview'
      preLoaderRoute: typeof Admin2OverviewRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/reset-password': {
      id: '/admin2/reset-password'
      path: '/reset-password'
      fullPath: '/admin2/reset-password'
      preLoaderRoute: typeof Admin2ResetPasswordRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/roster': {
      id: '/admin2/roster'
      path: '/roster'
      fullPath: '/admin2/roster'
      preLoaderRoute: typeof Admin2RosterRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/school-day-status': {
      id: '/admin2/school-day-status'
      path: '/school-day-status'
      fullPath: '/admin2/school-day-status'
      preLoaderRoute: typeof Admin2SchoolDayStatusRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/signin': {
      id: '/admin2/signin'
      path: '/signin'
      fullPath: '/admin2/signin'
      preLoaderRoute: typeof Admin2SigninRouteImport
      parentRoute: typeof Admin2Route
    }
    '/student/signup': {
      id: '/student/signup'
      path: '/student/signup'
      fullPath: '/student/signup'
      preLoaderRoute: typeof StudentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/forgot-password': {
      id: '/teacher/forgot-password'
      path: '/teacher/forgot-password'
      fullPath: '/teacher/forgot-password'
      preLoaderRoute: typeof TeacherForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/reset-password': {
      id: '/teacher/reset-password'
      path: '/teacher/reset-password'
      fullPath: '/teacher/reset-password'
      preLoaderRoute: typeof TeacherResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/signin': {
      id: '/teacher/signin'
      path: '/teacher/signin'
      fullPath: '/teacher/signin'
      preLoaderRoute: typeof TeacherSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/signup': {
      id: '/teacher/signup'
      path: '/teacher/signup'
      fullPath: '/teacher/signup'
      preLoaderRoute: typeof TeacherSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/checking': {
      id: '/volunteer/checking'
      path: '/volunteer/checking'
      fullPath: '/volunteer/checking'
      preLoaderRoute: typeof VolunteerCheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/dashboard': {
      id: '/volunteer/dashboard'
      path: '/volunteer/dashboard'
      fullPath: '/volunteer/dashboard'
      preLoaderRoute: typeof VolunteerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/request-access': {
      id: '/volunteer/request-access'
      path: '/volunteer/request-access'
      fullPath: '/volunteer/request-access'
      preLoaderRoute: typeof VolunteerRequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/special-added': {
      id: '/volunteer/special-added'
      path: '/volunteer/special-added'
      fullPath: '/volunteer/special-added'
      preLoaderRoute: typeof VolunteerSpecialAddedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/teaching': {
      id: '/volunteer/teaching'
      path: '/volunteer/teaching'
      fullPath: '/volunteer/teaching'
      preLoaderRoute: typeof VolunteerTeachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin2/students/': {
      id: '/admin2/students/'
      path: '/students'
      fullPath: '/admin2/students/'
      preLoaderRoute: typeof Admin2StudentsIndexRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/students/$rollNo': {
      id: '/admin2/students/$rollNo'
      path: '/students/$rollNo'
      fullPath: '/admin2/students/$rollNo'
      preLoaderRoute: typeof Admin2StudentsRollNoRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/volunteers/': {
      id: '/admin2/volunteers/'
      path: '/volunteers'
      fullPath: '/admin2/volunteers/'
      preLoaderRoute: typeof Admin2VolunteersIndexRouteImport
      parentRoute: typeof Admin2Route
    }
    '/admin2/volunteers/$id': {
      id: '/admin2/volunteers/$id'
      path: '/volunteers/$id'
      fullPath: '/admin2/volunteers/$id'
      preLoaderRoute: typeof Admin2VolunteersIdRouteImport
      parentRoute: typeof Admin2Route
    }
    '/reset-password/$uid/$token': {
      id: '/reset-password/$uid/$token'
      path: '/reset-password/$uid/$token'
      fullPath: '/reset-password/$uid/$token'
      preLoaderRoute: typeof ResetPasswordUidTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Admin2RouteChildren {
  Admin2AccessRequestsRoute: typeof Admin2AccessRequestsRoute
  Admin2AssignmentsRoute: typeof Admin2AssignmentsRoute
  Admin2CautionRoute: typeof Admin2CautionRoute
  Admin2DailyPngRoute: typeof Admin2DailyPngRoute
  Admin2DashboardRoute: typeof Admin2DashboardRoute
  Admin2ForgotPasswordRoute: typeof Admin2ForgotPasswordRoute
  Admin2HolidaysRoute: typeof Admin2HolidaysRoute
  Admin2OverviewRoute: typeof Admin2OverviewRoute
  Admin2ResetPasswordRoute: typeof Admin2ResetPasswordRoute
  Admin2RosterRoute: typeof Admin2RosterRoute
  Admin2SchoolDayStatusRoute: typeof Admin2SchoolDayStatusRoute
  Admin2SigninRoute: typeof Admin2SigninRoute
  Admin2IndexRoute: typeof Admin2IndexRoute
  Admin2StudentsRollNoRoute: typeof Admin2StudentsRollNoRoute
  Admin2VolunteersIdRoute: typeof Admin2VolunteersIdRoute
  Admin2StudentsIndexRoute: typeof Admin2StudentsIndexRoute
  Admin2VolunteersIndexRoute: typeof Admin2VolunteersIndexRoute
}

const Admin2RouteChildren: Admin2RouteChildren = {
  Admin2AccessRequestsRoute: Admin2AccessRequestsRoute,
  Admin2AssignmentsRoute: Admin2AssignmentsRoute,
  Admin2CautionRoute: Admin2CautionRoute,
  Admin2DailyPngRoute: Admin2DailyPngRoute,
  Admin2DashboardRoute: Admin2DashboardRoute,
  Admin2ForgotPasswordRoute: Admin2ForgotPasswordRoute,
  Admin2HolidaysRoute: Admin2HolidaysRoute,
  Admin2OverviewRoute: Admin2OverviewRoute,
  Admin2ResetPasswordRoute: Admin2ResetPasswordRoute,
  Admin2RosterRoute: Admin2RosterRoute,
  Admin2SchoolDayStatusRoute: Admin2SchoolDayStatusRoute,
  Admin2SigninRoute: Admin2SigninRoute,
  Admin2IndexRoute: Admin2IndexRoute,
  Admin2StudentsRollNoRoute: Admin2StudentsRollNoRoute,
  Admin2VolunteersIdRoute: Admin2VolunteersIdRoute,
  Admin2StudentsIndexRoute: Admin2StudentsIndexRoute,
  Admin2VolunteersIndexRoute: Admin2VolunteersIndexRoute,
}

const Admin2RouteWithChildren =
  Admin2Route._addFileChildren(Admin2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Admin2Route: Admin2RouteWithChildren,
  ToolkitRoute: ToolkitRoute,
  Admin1AttendanceDashboardRoute: Admin1AttendanceDashboardRoute,
  Admin1ForgotPasswordRoute: Admin1ForgotPasswordRoute,
  Admin1HistoryRoute: Admin1HistoryRoute,
  Admin1ResetPasswordRoute: Admin1ResetPasswordRoute,
  Admin1SigninRoute: Admin1SigninRoute,
  StudentSignupRoute: StudentSignupRoute,
  TeacherForgotPasswordRoute: TeacherForgotPasswordRoute,
  TeacherResetPasswordRoute: TeacherResetPasswordRoute,
  TeacherSigninRoute: TeacherSigninRoute,
  TeacherSignupRoute: TeacherSignupRoute,
  VolunteerCheckingRoute: VolunteerCheckingRoute,
  VolunteerDashboardRoute: VolunteerDashboardRoute,
  VolunteerRequestAccessRoute: VolunteerRequestAccessRoute,
  VolunteerSpecialAddedRoute: VolunteerSpecialAddedRoute,
  VolunteerTeachingRoute: VolunteerTeachingRoute,
  ResetPasswordUidTokenRoute: ResetPasswordUidTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
