# Generated by Django 6.1.1 on 2026-09-15 18:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0003_teacher_auth_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('assigned_class', models.CharField(choices=[('ClassA', 'Class A'), ('ClassB', 'Class B'), ('ClassC', 'Class C'), ('ClassD', 'Class D')], max_length=20)),
                ('task', models.CharField(choices=[('TEACHING', 'Teaching'), ('CHECKING', 'Checking')], max_length=20)),
                ('instruction', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='admin2/assignments/%Y/%m/%d/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_admin2_assignments', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin2_assignments', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-assignment_date', '-created_at'],
                'indexes': [models.Index(fields=['assignment_date'], name='admin2_volu_assignm_e8cb83_idx'), models.Index(fields=['volunteer', 'assignment_date'], name='admin2_volu_volunte_8e67fc_idx')],
            },
        ),
    ]
