# Generated by Django 6.1.1 on 2026-09-16 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0001_initial'),
        ('attendance', '0002_volunteerattendance_attendance_source'),
        ('teachers', '0003_teacher_auth_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerassignment',
            old_name='sent_at',
            new_name='email_sent_at',
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='email_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='email_status',
            field=models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='NOT_SENT', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='sender_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='VolunteerAccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CAUTION', 'Caution'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_volunteers', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admin2_status', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerXPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('source', models.CharField(choices=[('ATTENDANCE_PRESENT', 'Attendance Present'), ('ATTENDANCE_ABSENT', 'Attendance Absent'), ('SPECIAL_PRESENT', 'Special Added Present'), ('ADMIN_INCREASE', 'Admin Increase'), ('ADMIN_DECREASE', 'Admin Decrease')], max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xp_transaction', to='attendance.volunteerattendance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin2_xp_changes', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xp_transactions', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_volunteer_access_requests', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='admin2_volu_status_46acb4_idx'), models.Index(fields=['volunteer', 'status'], name='admin2_volu_volunte_f39ab5_idx')],
            },
        ),
        migrations.CreateModel(
            name='VolunteerCaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('absence_streak', models.PositiveIntegerField(default=3)),
                ('caution_date', models.DateField(default=django.utils.timezone.localdate)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_volunteer_cautions', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautions', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['volunteer', 'status'], name='admin2_volu_volunte_11625b_idx'), models.Index(fields=['status'], name='admin2_volu_status_ba5148_idx')],
            },
        ),
    ]
