# Generated by Django 6.1.1 on 2026-09-16 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0002_rename_sent_at_volunteerassignment_email_sent_at_and_more'),
        ('teachers', '0003_teacher_auth_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='volunteerassignment',
            constraint=models.UniqueConstraint(fields=('volunteer', 'assignment_date'), name='unique_volunteer_assignment_per_day'),
        ),
    ]
