# Generated by Django 6.1.1 on 2026-09-17 12:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0003_volunteerassignment_unique_volunteer_assignment_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerassignment',
            name='homework_attachment',
            field=models.FileField(blank=True, null=True, upload_to='admin2/homework/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='volunteerassignment',
            name='task',
            field=models.CharField(choices=[('TEACHING', 'Teaching'), ('CHECKING', 'Checking'), ('INVIGILATOR', 'Invigilator')], max_length=20),
        ),
        migrations.CreateModel(
            name='DailySchoolStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, unique=True)),
                ('status', models.CharField(choices=[('HOLIDAY', 'No Class / Holiday'), ('PLAYING_DAY', 'Playing Day'), ('REGULAR_CLASS', 'Regular Class')], default='REGULAR_CLASS', max_length=20)),
                ('playing_day_email_status', models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='NOT_SENT', max_length=20)),
                ('playing_day_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('playing_day_email_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_daily_school_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
