# Generated by Django 6.1.1 on 2026-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0004_volunteerassignment_homework_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerassignment',
            name='assigned_class',
            field=models.CharField(choices=[('ClassA', 'Class A'), ('ClassB', 'Class B'), ('ClassC', 'Class C'), ('ClassD', 'Class D'), ('ClassE', 'Class E')], max_length=20),
        ),
    ]
